### ISSUE TITLE
Please create a better Documentation

### ISSUE THREAD

**Issue by devilAPI** [ShayBox/TopGG-Voter#3]
I have some Prolems. in the config.json. what is this cookie thing?

**Comment by ShayBox** [comment]
I guess I didn't really intend for anyone to use this, since it may be patched at any time.
The cookie config setting is the cookie from your browser for top.gg, its your login session, you have to be logged in to vote.

**Comment by devilAPI** [comment]
Okay thanks!

**Comment by devilAPI** [comment]
But how can i get it?

**Comment by devilAPI** [comment]
nvm, i got it
