### ISSUE TITLE
Suggestions for improvement (possible remuneration)

### ISSUE THREAD

**Issue by OiziZ** [ShayBox/TopGG-Voter#4]
Hello, I want to know if you can make some changes including:
The possibility of adding proxies for each vote,
To be able to set several cookies.
I can pay you for doing this.
Here is my discord: [0xOxane] OiziZ # 6333
cordially

**Comment by ShayBox** [comment]
I'll look into adding some more features

**Comment by ShayBox** [comment]
I pushed a commit that adds proxy support and multiple bot, cookie, and proxy support, try it out and see if it works, I don't do any proxy verification so you have to make sure your proxies are tested before use

**Comment by OiziZ** [comment]
Hello, the changes you make are working fine, (I'm in the process of modifying it to add 50 discord cookies).
However, I would have a job offered to you (if you don't mind). The program would be in js and without puppoteer (the bot will be on a nodejs vps)
cordially

**Comment by ShayBox** [comment]
I can do that

**Comment by OiziZ** [comment]
Can we talk through discord? Here is my discord: [0xOxane] OiziZ # 6333
cordially
